routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AuthTeacherController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RqserveController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\RqorderController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\StarController;
use App\Http\Controllers\SuggestionController;
use App\Http\Controllers\VisitorController;
use App\Models\Star;

/*

|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/pro')->middleware('guest:admin')->group(function () {
    Route::get('{guard}/login', [AuthController::class, 'showLogin'])->name('loginadmin');
    Route::post('/login', [AuthController::class, 'login']);
});

Route::prefix('admin/')->middleware('auth:admin')->group(function () {
    Route::get('', [DashboardController::class, 'show_Dashboard'])->name('dashboard');
    Route::resource('admins', AdminController::class);
    Route::resource('cities', CityController::class);
    Route::get('edit-password', [AuthController::class, 'editPassword'])->name('edit-password');
    Route::PUT('Update-password', [AuthController::class, 'updatePassword'])->name('Update-password');
    Route::get('edit_profile', [AuthController::class, 'edit_profile'])->name('edit_profile');
    Route::get('edit_profile_imgae', [AuthController::class, 'edit_profile_image'])->name('edit_profile_image');
    Route::PUT('Update-profile', [AuthController::class, 'updat_profile'])->name('Update-profile');
    Route::PUT('Update-profile_image/{id}', [AuthController::class, 'updat_profile_image'])->name('Update-profile_image');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::resource('categories', CategoryController::class);
    Route::resource('pages', PageController::class);
    Route::get('student_management', [DashboardController::class, 'student'])->name('student_management.index');
    Route::get('teacher_management', [DashboardController::class, 'teacher'])->name('teacher_management.index');
    Route::post('search/search_admin', [SearchController::class, 'search_admin'])->name('search_admin');
    // Route::get('show_serves_admin/{id}', [AuthController::class, 'ahmed_serve'])->name('ahmed.serve');
    Route::get('show_serves_admin/{id}', [SearchController::class, 'ahmed_serve'])->name('ahmed.show');
    Route::get('Ahmed_Oeder/{id}', [SearchController::class, 'Ahmed_Oeder'])->name('Ahmed_Oeder');
    Route::get('/Certain/Show/{id}', [HomeController::class, 'show_Certain_Admin'])->name('show.CertainAdmin');
    Route::get('/Certain/show_Certain_Edit/{id}', [HomeController::class, 'show_Certain_Edit'])->name('show_Certain_Edit');
    Route::resource('/control/services', ServiceController::class);
});
//----------------------------------------------------------------------------------------------------

Route::prefix('/')->middleware('guest:teacher,student')->group(function () {
    Route::get('{guard}/login', [AuthTeacherController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthTeacherController::class, 'login']);
});



// الراوتات الخاصة بتعديل والحذف للادمن
Route::prefix('admin/')->middleware('auth:admin')->group(function () {
});





// Route::view('/', 'index')->name('Home'); // الرئيسية
Route::get('', [VisitorController::class, 'index'])->middleware('guest:teacher,student')->name('Home'); //   الرئيسية


Route::prefix('/register')->group(function () {
    Route::resource('student', StudentController::class);
    Route::resource('teacher', TeacherController::class);
    Route::get('logout_log', [AuthTeacherController::class, 'logout'])->name('logout_log');
});

//----------------------------------------------------------------------------------------------------

Route::get('/showindex', [HomeController::class, 'showindex'])->name('showindex')->middleware(['auth:teacher,student']); // المعلمين وخدماتهم

Route::get('/Home', [HomeController::class, 'showHome'])->name('showHome')->middleware(['auth:teacher,student']); // المعلمين وخدماتهم
Route::get('/requests_Std', [HomeController::class, 'requests_Std'])->name('requests_Std')->middleware('auth:teacher,student'); // الطلاب واحتياجاتهم

Route::prefix('/profile')->middleware('auth:teacher,student')->group(function () {
    Route::get('/', [HomeController::class, 'showprofile'])->name('showprofile');
    Route::get('/control', [HomeController::class, 'profile_settings'])->name('control');
    Route::resource('/control/services', ServiceController::class);
    Route::resource('/control/Profile/Edite/image', ImageController::class);
    // Route::get('/control/servicesshow/{services}', [HomeController::class, 'show_Service'])->name('show_Service');
    Route::get('/Edite_Profile', [HomeController::class, 'Edite_Profile'])->name('Edite_Profile');
    Route::put('/profile_setting/{id}', [HomeController::class, 'profile_update'])->name('profile_update');
    Route::get('/profile_setting/password_edit', [HomeController::class, 'password_edit'])->name('password_edit');
    Route::PUT('/profile_setting/Password/update_Password', [HomeController::class, 'update_Password'])->name('update_Password');
    // Route::get('/Show_Profile/{id}', [HomeController::class, 'Show_Profile'])->name('Show_Profile');
});


Route::prefix('/profile')->middleware('auth:teacher,student')->group(function () {
    Route::get('/control/std', [HomeController::class, 'profile_settings_std'])->name('control_std');
    Route::get('/show/student/{id}', [HomeController::class, 'show'])->name('show.std');
    Route::get('/show/teacher/{id}', [HomeController::class, 'show_teacher'])->name('show.teacher');
    Route::resource('/control/services', ServiceController::class);
    Route::resource('/control/order', OrderController::class);
    // Route::get('/control/servicesshow/{services}', [HomeController::class, 'show_Service'])->name('show_Service');
    Route::get('/Edite_Profile', [HomeController::class, 'Edite_Profile'])->name('Edite_Profile');
    Route::put('/profile_setting/{id}', [HomeController::class, 'profile_update'])->name('profile_update');
    Route::get('/profile_setting/password_edit', [HomeController::class, 'password_edit'])->name('password_edit');
    Route::PUT('/profile_setting/Password/update_Password', [HomeController::class, 'update_Password'])->name('update_Password');
});

//-------------complete medicine-----------------------------------------------------order route ----------------------------------------------------------------

Route::prefix('/serves')->middleware('auth:admin')->group(
    function () {
        Route::resource('/boxing', SuggestionController::class);
    }
);




Route::prefix('/serves')->middleware('auth:teacher,student')->group(function () {
    Route::get('/complete-medicine/{id}', [HomeController::class, 'Reqserves'])->name('complete_oeder');

    Route::resource('Certain', RqserveController::class);
    Route::resource('Notice', NoticeController::class);

    Route::get('/Certain/Show/{id}', [HomeController::class, 'show_Certain'])->name('show.Certain');
    Route::get('/Certain/Show/read/{id}', [HomeController::class, 'show_CertainPro'])->name('show.CertainPro');
    Route::get('/Certain/Show/Accept/{id}', [HomeController::class, 'Accept'])->name('show.Accept');
    Route::put('/Certain/Show/Accept/Satus/{id}', [HomeController::class, 'Accept_UPdate'])->name('Accept.UPdate');
    Route::get('/Certain/Show/read/std/read/all/{id}', [HomeController::class, 'read_all'])->name('read_all');


    Route::resource('Certain/rqstd', RqorderController::class);
    Route::get('/complete-medicine/Rqorder/{id}', [HomeController::class, 'Rqorder'])->name('complete_oederstd');
    Route::get('/Certain/Show/std/{id}/', [HomeController::class, 'showstd_Certain'])->name('showstd.Certain');
    Route::get('/Certain/Show/read/std/{id}', [HomeController::class, 'show_CertainProstd'])->name('show.CertainProstd');
    Route::get('/Certain/Show/read/std/read_all/{id}', [HomeController::class, 'read_allstd'])->name('read_allstd');


    Route::get('/View/all/notificationsstd/{id}', [HomeController::class, 'view_allstd'])->name('view_allstd');
    Route::get('/View/all/notifications/teach/{id}', [HomeController::class, 'view_all'])->name('view_all');
    //--------------------------------------------------------------عرض كافة الطلبات الواردة----------------------------------------------------------
    Route::get('/View/all/notifications/Incoming_requests/', [HomeController::class, 'rqserve_all'])->name('rqserve_all');
    Route::get('/View/all/notifications/Incoming_requests_std/', [HomeController::class, 'rqserve_allstd'])->name('rqserve_allstd');

    Route::Delete('destroy/{id}', [HomeController::class, 'destroy'])->name('destroy');
    Route::Delete('destroy_N/{id}', [HomeController::class, 'destroy_N'])->name('destroy_N');
    Route::put('update/image/{id}', [AuthController::class, 'updat_image'])->name('image.update');


    Route::get('/View/all/notifications/Incoming_requests_std/std_allserve', [HomeController::class, 'std_allserve'])->name('std_allserve');

resources/views/Show_profile.blade.php
@extends('layout.parent')


@section('Title', 'الملف الشخصي')

@section('CSS')

    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

    <link href="{{ asset('assets/css/Star.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/profile.css') }}" rel="stylesheet">


@endsection

@section('content')


@section('Top')
    <section id="topbar">
        <div class="container d-flex justify-content-center justify-content-md-between" id="topb">
            <div class="contact-info d-flex align-items-center">
                <a href="mailto:ahmed8051741@gmail.com" class="visitor"> &nbsp; الدعم الفني عبر البريد الالكتروني </a>
            </div>
            <div class="d-flex flex-row align-items-center feed-text px-2" dir="ltr">
                &nbsp;&nbsp;
                <div class="d-flex flex-column flex-wrap ml-2"><span class="font-weight-bold">
                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" style="color: #ffffff;"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img class="rounded-circle" src="assets/img/my.jpeg" width="42"> &nbsp;&nbsp;
                                {{ auth()->user()->name }} &nbsp;</a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{{ route('showprofile') }}">الملف الشخصي</a>
                                <hr style="margin-top:0.8px;margin-bottom:0.8px">
                                <a class="dropdown-item" href="{{ route('services.create') }}">اضافة خدمة جديد</a>
                                <a class="dropdown-item" href="{{ route('control') }}">لوحة القيادة</a>
                                <a class="dropdown-item" href="{{ route('logout_log') }}">تسجيل الخروج</a>
                            </div>
                        </div>
                    </span>

                </div>
            </div>
        </div>
    </section>
@endsection

@section('dd')
    <a href="mailto:ahmed8051741@gmail.com" class="visitor"> &nbsp; الدعم الفني عبر البريد الالكتروني
    </a>
@endsection
<div class="container bootstrap snippets bootdey">
    <div class="row">
        <div class="profile-nav col-md-3">
            <div class="panel">
                <div class="user-heading round">
                    <a href="#">
                        <img src="{{ asset('storage/image_profile/' . $teacher->image) }}" alt="">
                    </a>
                    <h1> {{ $teacher->name }}</h1>
                    <p> التخصص :

                        @if ($teacher->major == null)
                            لم يتم اختيار التخصص بعد
                        @else
                            {{ $teacher->major }}
                        @endif

                    </p>
                    <p> هاتف :
                        @if ($teacher->mobile == null)
                            لا يوجد رقم هاتف

                        @else
                            {{ $teacher->mobile }}

                        @endif

                </div>

                <ul class="nav">

                    <li class="active"><a href=" "><i class="fa fa-user"> &nbsp;</i>
                            الملف
                            الشخصي</a></li>
                    @if ($teacher->email != null)
                        <li><a href="mailto:{{ $teacher->email }}" target="_blank"><i class="far fa-envelope">
                                    &nbsp;</i>
                                تواصل من
                                خلال البريد الالكتروني </a></li>
                    @endif
                    @if ($teacher->facebook != null)

                        <li><a href="{{ $teacher->facebook }}" target="_blank"><i class="fab fa-facebook-square">
                                    &nbsp;</i> تواصل من
                                خلال فيسبوك
                                بوك</a></li>
                    @endif

                    @if ($teacher->mobile != null)

                        <li><a href="https://wa.me/{{ $teacher->s_mobile }}{{ $teacher->mobile }}"
                                target="_blank"><i class="fab fa-whatsapp" style="  font-size: 14px"> &nbsp;</i>
                                تواصل من خلال واتس
                                اب </a>
                        </li>
                    @endif

                    @if ($teacher->instagram != null)

                        <li><a href="https://wa.me/{{ $teacher->instagram }}" target="_blank"><i
                                    class="fab fa-instagram" style="  font-size: 14px"> &nbsp;</i>
                                تواصل من خلال انستجرام </a>
                        </li>
                    @endif
                    @if ($teacher->youtube != null)

                        <li><a href="{{ $teacher->youtube }}" target="_blank"><i class="fab fa-youtube">
                                    &nbsp;</i>الذهاب
                                الى قناه
                                اليوتيوب
                            </a></li>
                    @endif



                </ul>
            </div>
        </div>
        <div class="profile-info col-md-9">
            <div class="panel">
                <div class="bg-info clearfix">
                    <button type="button" class="btn btn-secondary float-right"> الملف الشخصي </button>
                </div>
            </div>
            <div class="panel">

                <div class="panel-body bio-graph-info">
                    <div style="margin: 5px; margin-right: 16px;margin-top:20px; ">
                        <h4> نبذة تعريفية عن {{ $teacher->name }} </h4>
                        <div align="center">
                            <hr width="96%">
                        </div>


                        <div class="row" style="margin: 5px;margin-top: 25px">
                            <div align="center">
                                <p style="text-align: right ; width: 80%"><span>
                                        @if ($teacher->describe == null)
                                            لم
                                            يتم اضافة اي وصف
                                            <span style="color: red"> لذالك نحن لا ننصح بتعامل مع هذا المدرس </span>
                                        @else
                                            {{ $teacher->describe }}
                                        @endif
                                    </span>
                                </p>
                            </div>
                        </div>
                        {{-- @if (auth()->user()->account_type == 'student')

                            <div style="margin: 5px; margin-right: 16px ">
                                <div align="center">
                                    <hr width="96%">
                                </div>

                                <div>

                                    <form action="">

                                        <span style="font-size: 18px ; text-align: right" dir="rtl"> قيم هذا المعلم :
                                        </span>
                                        <input class="star star-5" id="star-5-2" type="radio" name="star" value="5" />
                                        <label class="star star-5" for="star-5-2"></label>
                                        <input class="star star-4" id="star-4-2" type="radio" value="4" name="star" />
                                        <label class="star star-4" for="star-4-2"></label>
                                        <input class="star star-3" id="star-3-2" type="radio" name="star" value="3" />
                                        <label class="star star-3" for="star-3-2"></label>
                                        <input class="star star-2" id="star-2-2" type="radio" name="star" value="2" />
                                        <label class="star star-2" for="star-2-2"></label>
                                        <input class="star star-1" id="star-1-2" type="radio" name="star" value="1" />
                                        <label class="star star-1" for="star-1-2"></label>
                                        <p style="color: red;"> تحذير لن تتمكن من التراجع عن هذا التقيم لاحقاً في
                                            الوقت
                                            الحالي </p>

                                        <input type="text" value="{{ auth()->user()->id }}">
                                        <input type="text" value="{{ $teacher->id }}">
                                        <div class="card">

                                            <br>
                                            <br>
                                            <button type="submit" class="btn btn-primary" id="button">
                                                تأكيد التقيم </button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        @endif --}}

                    </div>
                </div>

                <div>

                    <br>
                    <br>
                    <br>

                </div>
                <br>
            </div>
        </div>
    </div>

    <br>
    <br>
    <br>

</div>



@endsection


@section('JS')



<script>
    function store(id) {
        Swal.fire({

            title: 'تحذير !',
            text: 'لن تتمكن من التراجع عن التقيم او تعديلة لاحقاً  ..!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            cancelButtonText: 'الغاء',
            confirmButtonText: 'نعم ، اكمل من فضلك',
        }).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {
                axios.post('/serves/Certain/rqstd/', {
                        order: document.getElementById('order').value,
                    })
                    .then(function(response) {
                        // handle success
                        console.log(response);
                        toastr.success(response.data.message);
                        // document.getElementById('create-form').reset(); // تصفير قيمة الفورم سبمت
                        window.location.href = "/profile/show/teacher/" + id; // التحويل والانتقال
                    })
                    .catch(function(error) {
                        // handle error
                        console.log(error);
                        toastr.error(error.response.data.message);
                    })
                    .then(function() {
                        // always executed
                    });
            }
        })
    }
</script>
@endsection

resources/views/boxing.blade.php
@extends('layout.parent')


@section('Title', 'اضافة خدمه')

@section('CSS')

    <link href="{{ asset('assets/css/Star.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/profile.css') }}" rel="stylesheet">
    <style>
        .custom-file {
            position: relative;
            display: inline-block;
            width: 100%;
            height: calc(2.25rem + 2px);
            margin-bottom: 0;
        }

        .custom-file-input {
            position: relative;
            z-index: 2;
            width: 100%;
            height: calc(2.25rem + 2px);
            margin: 0;
            opacity: 0;
        }

        .custom-file-label {
            position: absolute;
            font-family: 'cairo';
            top: 0;
            left: 0;
            right: 0;
            z-index: 1;
            height: calc(2.25rem + 2px);
            padding: .375rem .75rem;
            font-weight: 400;
            line-height: 1.5;
            color: #495057;
            background-color: rgb(235, 235, 235);
            border: 1px solid #ced4da;
            border-radius: .25rem;
        }

        #header {
            visibility: hidden;
            margin-top: -50px;
        }

    </style>

@endsection

@section('dd')
    <h2 class="logo" style="font-family: Al-Jazeera-Arabic"><a href="{{ route('showHome') }}"
            style="font-family: Al-Jazeera-Arabic; color: aliceblue"> Learn <span
                style="font-family: Al-Jazeera-Arabic;font-weight: 760;color: #Fd4;"> up
            </span></a></h2>
@endsection
@section('con', 'display: none')


@section('content')
    <div class="container bootstrap snippets bootdey">
        <div class="row">

            <div class="profile-nav col-md-3">
                <div class="panel">
                    <div class="user-heading round">
                        <a href="#">
                            <img src="{{ asset('storage/image_profile/' . auth()->user()->image) }}" alt="">
                        </a>
                        <h1> {{ auth()->user()->name }} </h1>
                        <p>{{ auth()->user()->email }} </p>
                    </div>
                    <ul class="nav">
                        <li><a href="{{ route('control') }}"><i class="fas fa-tachometer-alt">
                                    &nbsp;</i>
                                دفقة القيادة </a></li>
                        <li><a href="{{ route('showprofile') }}"><i class="fa fa-user"> &nbsp;</i> الملف الشخصي </a>
                        </li>

                        @if (auth()->user()->id == auth('teacher')->id())
                            <li><a href="{{ route('services.index') }}"><i class="fab fa-servicestack">
                                        &nbsp;</i>
                                    الخدمات
                                </a></li>

                            <li><a href="{{ route('rqserve_all') }}"><i class="fas fa-retweet"> &nbsp;</i>
                                    الطلبات الواردة
                                </a></li>
                        @else
                            <li><a href="{{ route('order.index') }}"><i class="fab fa-servicestack"> &nbsp;</i>
                                    الطلبات
                                </a></li>


                            <li><a href="{{ route('rqserve_allstd') }}"><i class="fas fa-retweet"> &nbsp;</i>
                                    العروض المقدمه
                                </a></li>
                        @endif

                                     <li  class="active"><a href="{{ route('boxing.create') }}"><i class="fas fa-box-open"> &nbsp;</i>
                                        صندوق الاقتراحات
                                </a></li>


                        <li><a href="{{ route('password_edit') }}"><i class="fas fa-lock"> &nbsp;</i> تعديل كلمه
                                المرور</a></li>



                        <li><a href="{{ route('logout_log') }}"><i class="fas fa-sign-out-alt"> &nbsp;</i> تسجيل
                                الخروج</a></li>
                    </ul>

                </div>
            </div>
            <div class="profile-info col-md-9" style="margin-bottom: 60px">
                <div class="panel">
                    <div class="bg-info clearfix">
                        <button type="button" class="btn btn-secondary float-right"> صندوق الاقتراحات </button>
                    </div>
                </div>


                <div class="card">
                    <div class="card-header" style="padding-top: 13px;padding-bottom: 12px;padding-right:18px;width: 100%;">


                        <div class="col-8">
                            <h4> صندوق الاقتراحات </h3>
                        </div>


                    </div>


                    <!-- /.card-header -->
                    <div class="card-body">

                        <form>


                              <div class="form-group row">
                                <label for="describe" class="col-12 col-form-label mb-2" style="color: rgb(0, 0, 0)"> ادخل ما تود اقتراحه هنا - او ادخل مشكلتك ان كان لديك مشكلة </label>
                                <div class="col-12">
                                    <textarea id="describe" cols="40" rows="4" class="form-control"> </textarea>
                                </div>
                            </div>

                             <br>
                            <br>

                            <button type="button" onclick="store()" class="btn btn-primary"
                                id="button" style="float: left; width: 100%"> ارسل الاقتراح </button>
                            <br>
                            <br>
                            <br>
                        </form>
                    </div>

                    <!-- /.card-body -->
                </div>

            </div>



        @endsection


        @section('JS')

          <script>
    function store(id) {
        Swal.fire({

            title: 'تحذير !',
            text: 'لن تتمكن من الغاء هذه العملية او التعديل عليها هل انت متأكد من الأرسال الى مدير النظام',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            cancelButtonText: 'الغاء',
            confirmButtonText: 'نعم ، اكمل من فضلك',
        }).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {
                axios.post('/serves/boxing/', {
                        describe: document.getElementById('describe').value,
                    })
                    .then(function(response) {
                        // handle success
                        console.log(response);
                        toastr.success(response.data.message);
                        document.getElementById('create-form').reset(); // تصفير قيمة الفورم سبمت
                        // window.location.href = "/profile/show/teacher/" + id; // التحويل والانتقال
                    })
                    .catch(function(error) {
                        // handle error
                        console.log(error);
                        toastr.error(error.response.data.message);
                    })
                    .then(function() {
                        // always executed
                    });
            }
        })
    }
</script>

        @endsection