routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AuthTeacherController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RqserveController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\RqorderController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\StarController;
use App\Http\Controllers\SuggestionController;
use App\Http\Controllers\VisitorController;
use App\Models\Star;

/*

|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/pro')->middleware('guest:admin')->group(function () {
    Route::get('{guard}/login', [AuthController::class, 'showLogin'])->name('loginadmin');
    Route::post('/login', [AuthController::class, 'login']);
});

Route::prefix('admin/')->middleware('auth:admin')->group(function () {
    Route::get('', [DashboardController::class, 'show_Dashboard'])->name('dashboard');
    Route::resource('admins', AdminController::class);
    Route::resource('cities', CityController::class);
    Route::get('edit-password', [AuthController::class, 'editPassword'])->name('edit-password');
    Route::PUT('Update-password', [AuthController::class, 'updatePassword'])->name('Update-password');
    Route::get('edit_profile', [AuthController::class, 'edit_profile'])->name('edit_profile');
    Route::get('edit_profile_imgae', [AuthController::class, 'edit_profile_image'])->name('edit_profile_image');
    Route::PUT('Update-profile', [AuthController::class, 'updat_profile'])->name('Update-profile');
    Route::PUT('Update-profile_image/{id}', [AuthController::class, 'updat_profile_image'])->name('Update-profile_image');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::resource('categories', CategoryController::class);
    Route::resource('pages', PageController::class);
    Route::get('student_management', [DashboardController::class, 'student'])->name('student_management.index');
    Route::get('teacher_management', [DashboardController::class, 'teacher'])->name('teacher_management.index');
    Route::post('search/search_admin', [SearchController::class, 'search_admin'])->name('search_admin');
    // Route::get('show_serves_admin/{id}', [AuthController::class, 'ahmed_serve'])->name('ahmed.serve');
    Route::get('show_serves_admin/{id}', [SearchController::class, 'ahmed_serve'])->name('ahmed.show');
    Route::get('Ahmed_Oeder/{id}', [SearchController::class, 'Ahmed_Oeder'])->name('Ahmed_Oeder');
    Route::get('/Certain/Show/{id}', [HomeController::class, 'show_Certain_Admin'])->name('show.CertainAdmin');
    Route::get('/Certain/show_Certain_Edit/{id}', [HomeController::class, 'show_Certain_Edit'])->name('show_Certain_Edit');
    Route::resource('/control/services', ServiceController::class);
});
//----------------------------------------------------------------------------------------------------

Route::prefix('/')->middleware('guest:teacher,student')->group(function () {
    Route::get('{guard}/login', [AuthTeacherController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthTeacherController::class, 'login']);
});



// الراوتات الخاصة بتعديل والحذف للادمن
Route::prefix('admin/')->middleware('auth:admin')->group(function () {
});





// Route::view('/', 'index')->name('Home'); // الرئيسية
Route::get('', [VisitorController::class, 'index'])->middleware('guest:teacher,student')->name('Home'); //   الرئيسية


Route::prefix('/register')->group(function () {
    Route::resource('student', StudentController::class);
    Route::resource('teacher', TeacherController::class);
    Route::get('logout_log', [AuthTeacherController::class, 'logout'])->name('logout_log');
});

//----------------------------------------------------------------------------------------------------

Route::get('/showindex', [HomeController::class, 'showindex'])->name('showindex')->middleware(['auth:teacher,student']); // المعلمين وخدماتهم

Route::get('/Home', [HomeController::class, 'showHome'])->name('showHome')->middleware(['auth:teacher,student']); // المعلمين وخدماتهم
Route::get('/requests_Std', [HomeController::class, 'requests_Std'])->name('requests_Std')->middleware('auth:teacher,student'); // الطلاب واحتياجاتهم

Route::prefix('/profile')->middleware('auth:teacher,student')->group(function () {
    Route::get('/', [HomeController::class, 'showprofile'])->name('showprofile');
    Route::get('/control', [HomeController::class, 'profile_settings'])->name('control');
    Route::resource('/control/services', ServiceController::class);
    Route::resource('/control/Profile/Edite/image', ImageController::class);
    // Route::get('/control/servicesshow/{services}', [HomeController::class, 'show_Service'])->name('show_Service');
    Route::get('/Edite_Profile', [HomeController::class, 'Edite_Profile'])->name('Edite_Profile');
    Route::put('/profile_setting/{id}', [HomeController::class, 'profile_update'])->name('profile_update');
    Route::get('/profile_setting/password_edit', [HomeController::class, 'password_edit'])->name('password_edit');
    Route::PUT('/profile_setting/Password/update_Password', [HomeController::class, 'update_Password'])->name('update_Password');
    // Route::get('/Show_Profile/{id}', [HomeController::class, 'Show_Profile'])->name('Show_Profile');
});


Route::prefix('/profile')->middleware('auth:teacher,student')->group(function () {
    Route::get('/control/std', [HomeController::class, 'profile_settings_std'])->name('control_std');
    Route::get('/show/student/{id}', [HomeController::class, 'show'])->name('show.std');
    Route::get('/show/teacher/{id}', [HomeController::class, 'show_teacher'])->name('show.teacher');
    Route::resource('/control/services', ServiceController::class);
    Route::resource('/control/order', OrderController::class);
    // Route::get('/control/servicesshow/{services}', [HomeController::class, 'show_Service'])->name('show_Service');
    Route::get('/Edite_Profile', [HomeController::class, 'Edite_Profile'])->name('Edite_Profile');
    Route::put('/profile_setting/{id}', [HomeController::class, 'profile_update'])->name('profile_update');
    Route::get('/profile_setting/password_edit', [HomeController::class, 'password_edit'])->name('password_edit');
    Route::PUT('/profile_setting/Password/update_Password', [HomeController::class, 'update_Password'])->name('update_Password');
});

//-------------complete medicine-----------------------------------------------------order route ----------------------------------------------------------------

Route::prefix('/serves')->middleware('auth:admin')->group(
    function () {
        Route::resource('/boxing', SuggestionController::class);
    }
);




Route::prefix('/serves')->middleware('auth:teacher,student')->group(function () {
    Route::get('/complete-medicine/{id}', [HomeController::class, 'Reqserves'])->name('complete_oeder');

    Route::resource('Certain', RqserveController::class);
    Route::resource('Notice', NoticeController::class);

    Route::get('/Certain/Show/{id}', [HomeController::class, 'show_Certain'])->name('show.Certain');
    Route::get('/Certain/Show/read/{id}', [HomeController::class, 'show_CertainPro'])->name('show.CertainPro');
    Route::get('/Certain/Show/Accept/{id}', [HomeController::class, 'Accept'])->name('show.Accept');
    Route::put('/Certain/Show/Accept/Satus/{id}', [HomeController::class, 'Accept_UPdate'])->name('Accept.UPdate');
    Route::get('/Certain/Show/read/std/read/all/{id}', [HomeController::class, 'read_all'])->name('read_all');


    Route::resource('Certain/rqstd', RqorderController::class);
    Route::get('/complete-medicine/Rqorder/{id}', [HomeController::class, 'Rqorder'])->name('complete_oederstd');
    Route::get('/Certain/Show/std/{id}/', [HomeController::class, 'showstd_Certain'])->name('showstd.Certain');
    Route::get('/Certain/Show/read/std/{id}', [HomeController::class, 'show_CertainProstd'])->name('show.CertainProstd');
    Route::get('/Certain/Show/read/std/read_all/{id}', [HomeController::class, 'read_allstd'])->name('read_allstd');


    Route::get('/View/all/notificationsstd/{id}', [HomeController::class, 'view_allstd'])->name('view_allstd');
    Route::get('/View/all/notifications/teach/{id}', [HomeController::class, 'view_all'])->name('view_all');
    //--------------------------------------------------------------عرض كافة الطلبات الواردة----------------------------------------------------------
    Route::get('/View/all/notifications/Incoming_requests/', [HomeController::class, 'rqserve_all'])->name('rqserve_all');
    Route::get('/View/all/notifications/Incoming_requests_std/', [HomeController::class, 'rqserve_allstd'])->name('rqserve_allstd');

    Route::Delete('destroy/{id}', [HomeController::class, 'destroy'])->name('destroy');
    Route::Delete('destroy_N/{id}', [HomeController::class, 'destroy_N'])->name('destroy_N');
    Route::put('update/image/{id}', [AuthController::class, 'updat_image'])->name('image.update');


    Route::get('/View/all/notifications/Incoming_requests_std/std_allserve', [HomeController::class, 'std_allserve'])->name('std_allserve');

resources/views/admins/admin/create.blade.php
@extends('admins.parent')

@section('title', 'انشاء مشرف')
@section('bige-title', 'انشاء مشرف')
@section('main-page', 'الرئيسية')
@section('sub-page', 'المشرفين')
@section('himen', 'menu-open')

@section('content')
<!-- Main content -->
<section class="content">
<div class="container-fluid">
<div class="row" dir="rtl">
<!-- left column -->
<div class="col-md-12">
<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: right"> انشاء مشرف </h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form id="create-form" dir="rtl">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="name">الأسم</label>
                <input type="text" class="form-control" id="name" placeholder="ادخل اسم المشرف الجديد">
            </div>
            <div class="form-group">
                <label for="name">البريد الالكتروني</label>
                <input type="text" class="form-control" id="email" placeholder="ادخل البريد الالكتروني">
            </div>



            <div class="form-group">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="active">
                    <label class="custom-control-label" for="active">تفعيل الحساب</label>
                </div>
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="button" onclick="store()" class="btn btn-primary" id="button">ادخال
                وحفظ</button>
        </div>
    </form>
</div>


</div>

</div>
<!-- /.row -->
</div><!-- /.container-fluid -->
</section>

@endsection

@section('JS')
<script>
    function store() {
        axios.post('/admin/admins/', {
                name: document.getElementById('name').value,
                email: document.getElementById('email').value,
                active: document.getElementById('active').checked

            })
            .then(function(response) {
                // handle success
                console.log(response);
                toastr.success(response.data.message);
                // document.getElementById('create-form').reset(); // تصفير قيمة الفورم سبمت
                setTimeout(function() {
                    window.location.href = "/admin/admins/"; // التحويل والانتقال
                }, 1500);
            })
            .catch(function(error) {
                // handle error
                console.log(error);
                toastr.error(error.response.data.message);
            })
            .then(function() {
                // always executed
            });
    }
</script>
@endsection

resources/views/admins/admin/edit.blade.php
@extends('admins.parent')
@section('title', 'تعديل بينات المشرف')
@section('bige-title', 'تعديل بينات المشرف')
@section('main-page', 'الرئيسية')
@section('sub-page', 'تعديل المشرف')
@section('profile', 'Active')

@section('content')
<!-- Main content -->
<section class="content">
<div class="container-fluid">
<div class="row">
<!-- left column -->
<div class="col-md-12">
<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: right">تعديل بينات المشرف</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form id="create-form">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="name">الاسم</label>
                <input type="text" class="form-control" id="name" placeholder="ادخل الاسم"
                    value="{{ $admin->name }}">
            </div>

            <div class="form-group">
                <label for="name">البريد الالكتروني</label>
                <input type="text" class="form-control" id="email" placeholder="ادخل البريد الالكتروني"
                    value="{{ $admin->email }}">
            </div>

            {{-- @if ($admin->id != auth('admin')->id()) --}}


            <br>
            <div class="form-group">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="active" @if ($admin->id == auth('admin')->id()) disabled @endif @if ($admin->Active) checked @endif>
                    <label class="custom-control-label" for="active">تفعيل الحساب</label>
                </div>
            </div>
            {{-- @endif --}}

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            {{-- <button type="button" onclick="update({{$admin->id}}, '{{$admin->id !=auth('admin')->id()}}')" class="btn btn-primary" id="button">Update</button> --}}
            {{-- <button type="button" onclick="update({{$admin->id}},'{{$redirect ?? true}}')" class="btn btn-primary" id="button">Update</button> --}}
            <button type="button" onclick="Update()" class="btn btn-primary" id="button"> تحديث
                البينات</button>

        </div>
    </form>
</div>


</div>

</div>
<!-- /.row -->
</div><!-- /.container-fluid -->
</section>

@endsection

@section('JS')
<script>
    function Update() {
        axios.put('/admin/Update-profile/', {
                name: document.getElementById('name').value,
                email: document.getElementById('email').value,
                active: document.getElementById('active').checked
            })
            .then(function(response) {
                // handle success
                console.log(response);
                toastr.success(response.data.message);
                document.getElementById('create-form').reset(); // تصفير قيمة الفورم سبمت
                // window.location.href="/cms/admin/Update-password/"; // التحويل والانتقال
            })
            .catch(function(error) {
                // handle error
                console.log(error);
                toastr.error(error.response.data.message);
            })
            .then(function() {
                // always executed
            });
    }


    // function Update() {
    //     let formData = new FormData();
    //     formData.append('name', document.getElementById('name').value);
    //     formData.append('email', document.getElementById('email').value);
    //     formData.append('active', document.getElementById('active').checked ? 1 : 0);
    //     formData.append('images', document.getElementById('images').files[0]);
    //     axios.put('/admin/Update-profile/', formData)
    //         .then(function(response) {
    //             // handle success
    //             console.log(response);
    //             toastr.success(response.data.message);
    //             document.getElementById('create-form').reset();
    //         })
    //         .catch(function(error) {
    //             // handle error
    //             console.log(error);
    //             toastr.error(error.response.data.message);
    //         })
    //         .then(function() {
    //             // always executed
    //         });
    // }
</script>

@endsection

resources/views/admins/admin/edit_image.blade.php
@extends('admins.parent')
@section('title', 'تعديل بينات المشرف')
@section('bige-title', 'تعديل بينات المشرف')
@section('main-page', 'الرئيسية')
@section('sub-page', 'تعديل المشرف')
@section('profile_img', 'Active')

@section('content')
<!-- Main content -->
<section class="content">
<div class="container-fluid">
<div class="row">
<!-- left column -->
<div class="col-md-12">
<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: right">تعديل صورة المشرف</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form id="create-form">
        @csrf
        <div class="card-body">




            <div class="form-group">
                <!-- <label for="customFile">Custom File</label> -->

                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="image">
                    <label class="custom-file-label" for="image">Choose file</label>
                </div>
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            {{-- <button type="button" onclick="update({{$admin->id}}, '{{$admin->id !=auth('admin')->id()}}')" class="btn btn-primary" id="button">Update</button> --}}
            {{-- <button type="button" onclick="update({{$admin->id}},'{{$redirect ?? true}}')" class="btn btn-primary" id="button">Update</button> --}}
            <button type="button" onclick="update({{ auth()->user()->id }})" class="btn btn-primary"
                id="button"> تحديث
                الصورة</button>

        </div>
    </form>
</div>


</div>

</div>
<!-- /.row -->
</div><!-- /.container-fluid -->
</section>

@endsection

@section('JS')

<script>
    function update(id) {
        let formData = new FormData();
        formData.append('_method', 'PUT');
        formData.append('image', document.getElementById('image').files[0]);
        axios.post('/admin/Update-profile_image/' + id, formData)
            .then(function(response) {
                // handle success
                console.log(response);
                toastr.success(response.data.message);
                // document.getElementById('create-form').reset();
                // window.location.href = "/profile";
                // window.location.reload(10000);
                setTimeout(function() {
                    window.location.href = '/admin/edit_profile_imgae/';
                }, 1500);

            }, 10000)
            .catch(function(error) {
                // handle error
                console.log(error);
                toastr.error(error.response.data.message);
            })
            .then(function() {
                // always executed
            });

    }
</script>

@endsection

resources/views/admins/admin/index.blade.php
@extends('admins.parent')

@section('title', 'المشرفين')
@section('bige-title', 'المشرفين')
@section('main-page', 'الرئيسية')
@section('sub-page', 'المشرفين')

@section('himen', 'menu-open')

@section('content')
<section class="content">
<div class="container-fluid">

<!-- /.row -->
<div class="row">
<div class="col-12">
<div class="card">
    <div class="card-header">
        <h3 class="card-title" style="float: right"> جدول عرض جميع المشرفين </h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap table-bordered table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>الاسم</th>
                    <th>البريد الالكتروني</th>
                    <th>الحالة</th>
                    <th>تاريخ الانشاء </th>
                    <th> تاريخ التعديل </th>
                    <th>الاعدات</th>

                </tr>
            </thead>
            <tbody>
                @foreach ($admins as $admin)
                    {{-- @if ($admin->id != auth('admin')->id()) --}}
                    <tr>
                        <td>{{ $admin->id }}</td>
                        <td>{{ $admin->name }}</td>
                        <td>{{ $admin->email }}</td>
                        {{-- <td>@if ($admin->active) Active @else Disabled @endif </td> --}}
                        {{-- <td>{{$admin->status}}</td> بدل مستدعي الاكتف بتدعي الكولم الوهمي الي عملتو بلمودل باسم ستيتس --}}
                        <td>
                            <span class="badge @if ($admin->Active) bg-success @else bg-danger @endif ">
                                {{ $admin->Status_Keyword }} </span>
                        </td>

                        <td>{{ $admin->created_at }}</td>
                        <td>{{ $admin->updated_at }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('admins.edit', $admin->id) }}" class="btn btn-info">
                                    <i class="fas fa-edit "></i>
                                </a>

                                <a href="#" class="btn btn-danger"
                                    onclick="confirmDestroy({{ $admin->id }}, this)">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    {{-- @endif --}}

                @endforeach


            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->
</div>
</div>
</div><!-- /.container-fluid -->
</section>
@endsection

@section('JS')


<script>
    //عملية الحذف
    function confirmDestroy(id, referince) {
        //    console.log("ID:"+id)    // ->?   (id) تستعمل لفحص الكي اذا تم تمريرة او لا


        Swal.fire({
            title: 'هل انت متأكد من عملية الحذف؟',
            text: "لن تتمكن من التراجع عن هذا!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            cancelButtonText: 'الغاء',
            confirmButtonText: 'نعم ، احذفها!',
        }).then((result) => {
            if (result.isConfirmed) {
                destroy(id, referince); // referince لاستقبال الذس من الرابط
            }
        })
    }

    function destroy(id, referince) {
        // Make a request for a user with a given ID
        axios.delete('/admin/admins/' + id)
            .then(function(response) {
                // handle success
                console.log(response);
                referince.closest('tr')
                    .remove(); //referince في فوق في الرابط او الاشرف وليس شرك ان يسمى بي  this الذي يتبع الى كلمه  referince لحذف الصف دون الحاجة الى تحديث الصفحة بلاستناد على المتغير
                ShowMessage(response.data); // لاستقبال الجايسون من الكنترولر ببيناته رسالة النجاح والايقونة
            })
            .catch(function(error) {
                // handle error
                console.log(error); // اسقبال رسائل وبينات الخطاء
                ShowMessage(error.response.data);
            })
            .then(function() {
                // دائماً منفذة لو بدي انفذ داله معينة في كل الحالات
            });

    }

    function ShowMessage(data) {
        Swal.fire({
            icon: data.icon, // طباعة الايقونة والاعنوان بناء على البينات المستقبلة من الكنترولر
            title: data.title,
            text: data.text,
            showConfirmButton: false,
            timer: 1500
        })
    }
</script>

@endsection